apiVersion: apps/v1
kind: Deployment
metadata:
  name: teslaweb
  labels:
    app: teslaweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: teslaweb
  template:
    metadata:
      labels:
        app: teslaweb
    spec:
      containers:
      - name: teslaweb
        image: zaralink/ultimate-cicd:replaceImageTag
        ports:
        - containerPort: 8080
